default: &default
  adapter: postgresql
  encoding: unicode
development:
  <<: *default
  database: vote_poll_dev
  username: root
  password: root
 

production:
  <<: *default
  database: vote_poll_dev
  username: root
  password: root